// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCmhl53ffTgxAKZdaBNHopDOxQnUR-ifw',
    appId: '1:179645553765:web:cfa02194c105e6409cba8c',
    messagingSenderId: '179645553765',
    projectId: 'ecommerceapp-76d52',
    authDomain: 'ecommerceapp-76d52.firebaseapp.com',
    storageBucket: 'ecommerceapp-76d52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZxzJ-DJCMo73HZ26YCh4cIXpNfikgqQQ',
    appId: '1:721981346070:android:265fdb1a57cee41a9d8037',
    messagingSenderId: '721981346070',
    projectId: 'nearsq',
    storageBucket: 'nearsq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRScU1CU7r7WETpyYB_1VkwhB6ZZpCPc',
    appId: '1:179645553765:ios:896f095b874138a09cba8c',
    messagingSenderId: '179645553765',
    projectId: 'ecommerceapp-76d52',
    storageBucket: 'ecommerceapp-76d52.appspot.com',
    androidClientId: '179645553765-5s1pnlq0ekd2vcoq3vb9a47lv4niv35f.apps.googleusercontent.com',
    iosClientId: '179645553765-konk9io84spri1adnkf9bb0unqeaso7c.apps.googleusercontent.com',
    iosBundleId: 'com.example.store',
  );

}